# Generated by Django 4.2.3 on 2023-08-01 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
        migrations.CreateModel(
            name='LibroReferencia',
            fields=[
                ('libro_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aplicacion.libro')),
                ('isbn', models.CharField(max_length=13)),
            ],
            bases=('aplicacion.libro',),
        ),
        migrations.CreateModel(
            name='LibroTexto',
            fields=[
                ('libro_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aplicacion.libro')),
                ('tema', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=50)),
            ],
            bases=('aplicacion.libro',),
        ),
    ]
